// <auto-generated />
using System;
using Marketing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marketing.Migrations
{
    [DbContext(typeof(MarketingDbContext))]
    partial class MarketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Marketing.Data.Tables.Application", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Marketing.Data.Tables.Bank", b =>
                {
                    b.Property<string>("Bic")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Bic");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Marketing.Data.Tables.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bic");

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Bic");

                    b.HasIndex("Code");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Marketing.Data.Tables.Bid", b =>
                {
                    b.HasOne("Marketing.Data.Tables.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("Bic");

                    b.HasOne("Marketing.Data.Tables.Application", "Application")
                        .WithMany()
                        .HasForeignKey("Code");
                });
#pragma warning restore 612, 618
        }
    }
}
